use_frameworks!

platform :ios, '13.0'

target 'OnDocCalendar_Example' do
  pod 'OnDocCalendar', :git => 'https://github.com/ONDOC/OnDocCalendar.git'

  target 'OnDocCalendar_Tests' do
    inherit! :search_paths

    
  end
end
